services:
  parkings-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    env_file:
      - .env
    volumes:
      - static-content:/app/static
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000/health-check']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:stable-alpine
    ports:
      - '5173:80'
      # - "443:443"  # SSL
    volumes:
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static-content:/var/www/app/static:ro
      # - ./ssl:/etc/nginx/ssl:ro  # SSL
    depends_on:
      - parkings-app
    restart: unless-stopped

volumes:
  static-content:
