name: Deploy to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/dev/parkings-frontend
            git pull origin master

            # Make deploy script executable
            chmod +x deploy.sh

            # Run deployment
            ./deploy.sh

            echo "Deployment completed successfully!"
